export const UNAUTHORIZED_CODE = 20_000;
export const UNAUTHORIZED_NAME = 'UNAUTHORIZED';
export const UNAUTHORIZED_MESSAGE = 'Unauthorized';

export const INSUFFICIENT_PERMISSIONS_CODE = 20_001;
export const INSUFFICIENT_PERMISSIONS_NAME = 'INSUFFICIENT_PERMISSIONS';
export const INSUFFICIENT_PERMISSIONS_MESSAGE = 'Insufficient permissions';
