name: Run tests

on:
  push:
    branches:
      - main
    paths: &shared_paths
      - 'packages/@contracts/**'
      - 'packages/@core/utils/**'
      - 'packages/@domain/**'
      - 'packages/@node/**'
      - 'workspaces/server/**'
      - 'infrastructures/server/Dockerfile'
      - 'infrastructures/server/server.conf'
      - '.dockerignore'
      - 'vitest.config.ts'
      - '.github/actions/prepare-nodejs-pnpm/**'
      - '.github/actions/build-docker-image/**'
      - '.github/actions/deploy-ec2/**'
      - 'package.json'
      - '.github/workflows/server-test.yml'
      - '.github/workflows/server-deploy.yml'
  pull_request:
    branches:
      - main
    paths: *shared_paths

permissions:
  contents: read

concurrency:
  group: server-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run all tests

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_DB: hono_monorepo_test
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Prepare Node.JS and pnpm
        uses: ./.github/actions/prepare-nodejs-pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: ''
